# Generated by Django 3.0.6 on 2020-05-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('title', models.CharField(max_length=255)),
                ('key', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
