# Generated by Django 3.0.6 on 2020-05-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_app', '0002_document_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pieces',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/original'),
        ),
    ]
