# Generated by Django 3.0.6 on 2020-05-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_app', '0003_auto_20200524_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='pieces',
        ),
        migrations.AddField(
            model_name='document',
            name='max_lines',
            field=models.IntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='document',
            name='sheet_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='original/'),
        ),
    ]
