# Generated by Django 3.0.6 on 2020-05-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_app', '0004_auto_20200524_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='copy_headers',
            field=models.BooleanField(default=True),
        ),
    ]
