# Generated by Django 3.0.6 on 2020-05-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_app', '0005_document_copy_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='count_headers',
            field=models.BooleanField(default=False),
        ),
    ]
